export const ANALYTICS_EVENTS = {
  SIMULATION_STARTED: 'simulation_started',
  SIMULATION_RESET: 'simulation_reset',
  DAO_SELECTED: 'dao_selected',
  GOV_RULE_CHANGED: 'gov_rule_changed',
  EXPORT_CSV: 'export_csv',
  EXPORT_JSON: 'export_json',
  COMPARISON_OPENED: 'comparison_opened',
  BRANCH_CREATED: 'branch_created',
  MULTI_RUN_STARTED: 'multi_run_started',
  THEME_TOGGLED: 'theme_toggled',
  TUTORIAL_STARTED: 'tutorial_started',
  TUTORIAL_COMPLETED: 'tutorial_completed',
  TAB_CHANGED: 'tab_changed',
  SCENARIO_EVENT_ADDED: 'scenario_event_added',
  CUSTOM_AGENT_INJECTED: 'custom_agent_injected',
  SHARE_CONFIG: 'share_config',
  TUTORIAL_SKIPPED: 'tutorial_skipped',
  RESEARCH_SWEEP_SUBMITTED: 'research_sweep_submitted',
  RESEARCH_EXPERIMENT_RUN: 'research_experiment_run',
  BOOKING_SUBMITTED: 'booking_submitted',
} as const;
