[project]
name = "dao_simulator_private"

[[services]]
name = "dao_simulator_private"
buildCommand = "npm run build"
startCommand = "npm run start"

[[services]]
name = "socket-server"
dockerfilePath = "Dockerfile.socket"
