/**
 * Calibration Loader
 *
 * Loads CalibrationProfile JSON files generated by compile_calibration.py
 * and provides them to the simulation engine for historically-calibrated digital twins.
 */

import * as fs from 'fs';
import * as path from 'path';
import type { SimulationSettings } from '../config/settings';
import { logger } from '../utils/logger';

// =============================================================================
// CALIBRATION PROFILE TYPES
// =============================================================================

export interface VotingProfile {
  avg_participation_rate: number;
  participation_distribution: number[];
  avg_votes_per_proposal: number;
  voter_concentration: number;
  approval_rate: number;
  avg_for_percentage: number;
  quorum_hit_rate: number;
  delegation_rate: number;
}

export interface ProposalProfile {
  avg_proposals_per_month: number;
  proposal_types: Record<string, number>;
  avg_voting_period_days: number;
  avg_choices_per_proposal: number;
  pass_rate: number;
  monthly_cadence: number[];
}

export interface DrawdownEvent {
  start_idx: number;
  end_idx: number;
  magnitude: number;
}

export interface MarketProfile {
  avg_daily_return: number;
  daily_volatility: number;
  avg_price_usd: number;
  price_range: [number, number];
  avg_market_cap: number;
  avg_daily_volume: number;
  correlation_to_eth: number;
  drawdown_events: DrawdownEvent[];
}

export interface ForumProfile {
  avg_topics_per_month: number;
  avg_posts_per_topic: number;
  avg_views_per_topic: number;
  top_categories: Record<string, number>;
  avg_post_length_chars: number;
  reply_rate: number;
  sentiment_keywords: Record<string, number>;
}

export interface VoterCluster {
  label: string;
  share: number;
  avg_voting_power: number;
  participation_rate: number;
  alignment_with_majority: number;
}

export interface ProtocolProfile {
  avg_tvl: number;
  tvl_trend: 'growing' | 'stable' | 'declining';
  avg_daily_fees: number;
  avg_daily_revenue: number;
}

export interface CalibrationProfile {
  dao_id: string;
  voting: VotingProfile;
  proposals: ProposalProfile;
  market: MarketProfile | null;
  forum: ForumProfile | null;
  voter_clusters: VoterCluster[];
  protocol: ProtocolProfile;
}

// =============================================================================
// CALIBRATION LOADER
// =============================================================================

const CALIBRATION_DIR = path.join(process.cwd(), 'results', 'historical', 'calibration');

export class CalibrationLoader {
  private static cache: Map<string, CalibrationProfile> = new Map();
  private static calibrationDir: string = CALIBRATION_DIR;

  /**
   * Set the calibration directory (for testing or custom paths)
   */
  static setCalibrationDir(dir: string): void {
    CalibrationLoader.calibrationDir = dir;
    CalibrationLoader.cache.clear();
  }

  /**
   * Load a calibration profile for a specific DAO
   */
  static load(daoId: string): CalibrationProfile | null {
    if (CalibrationLoader.cache.has(daoId)) {
      return CalibrationLoader.cache.get(daoId)!;
    }

    const filePath = path.join(CalibrationLoader.calibrationDir, `${daoId}_profile.json`);

    try {
      if (!fs.existsSync(filePath)) {
        return null;
      }

      const content = fs.readFileSync(filePath, 'utf-8');
      const profile = JSON.parse(content) as CalibrationProfile;

      // Validate minimum required fields
      if (!profile.dao_id || !profile.voting || !profile.proposals) {
        return null;
      }

      CalibrationLoader.cache.set(daoId, profile);
      return profile;
    } catch (error) {
      logger.warn(`Failed to load calibration profile for "${daoId}"`, error);
      return null;
    }
  }

  /**
   * Load all available calibration profiles
   */
  static loadAll(): Map<string, CalibrationProfile> {
    const profiles = new Map<string, CalibrationProfile>();

    try {
      if (!fs.existsSync(CalibrationLoader.calibrationDir)) {
        return profiles;
      }

      const files = fs.readdirSync(CalibrationLoader.calibrationDir);
      for (const file of files) {
        if (file.endsWith('_profile.json')) {
          const daoId = file.replace('_profile.json', '');
          const profile = CalibrationLoader.load(daoId);
          if (profile) {
            profiles.set(daoId, profile);
          }
        }
      }
    } catch (error) {
      logger.warn('Failed to read calibration directory', error);
    }

    return profiles;
  }

  /**
   * Check if a calibration profile exists for a DAO
   */
  static hasProfile(daoId: string): boolean {
    if (CalibrationLoader.cache.has(daoId)) {
      return true;
    }
    const filePath = path.join(CalibrationLoader.calibrationDir, `${daoId}_profile.json`);
    return fs.existsSync(filePath);
  }

  /**
   * Get list of available DAO IDs with calibration profiles
   */
  static getAvailableIds(): string[] {
    try {
      if (!fs.existsSync(CalibrationLoader.calibrationDir)) {
        return [];
      }
      return fs.readdirSync(CalibrationLoader.calibrationDir)
        .filter(f => f.endsWith('_profile.json'))
        .map(f => f.replace('_profile.json', ''));
    } catch (error) {
      logger.warn('Failed to list calibration profiles', error);
      return [];
    }
  }

  /**
   * Convert a CalibrationProfile into Partial<SimulationSettings>
   * to calibrate simulation behavior parameters from historical data.
   *
   * Derived settings and their clamped ranges:
   * - `voting_activity` ← `avg_participation_rate`, clamped to [0.005, 0.95]
   * - `proposal_creation_probability` ← `avg_proposals_per_month / 720`, clamped to [0.001, 0.05]
   * - `comment_probability` ← `forum.reply_rate`, clamped to [0.1, 0.9]
   * - `price_volatility` ← `daily_volatility / sqrt(24)`, clamped to [0.001, 0.1]
   * - `voteHerdingFactor` ← `voter_concentration * 0.4`, clamped to [0.05, 0.5]
   */
  static toSettings(profile: CalibrationProfile): Partial<SimulationSettings> {
    const settings: Partial<SimulationSettings> = {};

    // Voting behavior
    // Set votingActivity to the raw historical rate. Per-agent voting probabilities
    // are fine-tuned from voter cluster data in simulation.ts applyCalibrationVotingProbabilities().
    if (profile.voting) {
      settings.voting_activity = Math.max(0.005, Math.min(0.95, profile.voting.avg_participation_rate));
    }

    // Proposal creation rate
    // Convert avg proposals per month to per-step probability
    // 1 month ≈ 30 days × 24 steps/day = 720 steps
    if (profile.proposals) {
      const proposalsPerStep = profile.proposals.avg_proposals_per_month / 720;
      settings.proposal_creation_probability = Math.max(0.001, Math.min(0.05, proposalsPerStep));
    }

    // Forum/comment probability
    if (profile.forum) {
      settings.comment_probability = Math.max(0.1, Math.min(0.9, profile.forum.reply_rate));
    }

    // Market volatility
    if (profile.market) {
      // Scale daily volatility to per-step volatility (24 steps/day)
      // Volatility scales with sqrt(time), so per-step vol ≈ daily_vol / sqrt(24)
      const perStepVol = profile.market.daily_volatility / Math.sqrt(24);
      settings.price_volatility = Math.max(0.001, Math.min(0.1, perStepVol));
    }

    // Vote herding from voter concentration
    if (profile.voting) {
      // Higher voter concentration → higher herding factor
      settings.voteHerdingFactor = Math.max(0.05, Math.min(0.5, profile.voting.voter_concentration * 0.4));
    }

    // Disable multi-stage proposals for calibrated simulations.
    // With only ~2-3 voters per proposal, multi-stage temp_check adds noise
    // and bypasses the calibrated quorum in resolveBasicProposals().
    settings.proposal_temp_check_fraction = 0;

    return settings;
  }

  /**
   * Clear the profile cache
   */
  static clearCache(): void {
    CalibrationLoader.cache.clear();
  }
}
